name: Testing self hosted runner

on:
    workflow_dispatch: 
jobs:
    build_job:
        runs-on: [self-hosted, linux, main, prod-ubunut-runner]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Update the machine
              run: |
               sudo apt update
               sleep 1500s

